// The 99 Names, fetched from api.aladhan.com/v1/asmaAlHusna rather than
// written from memory. Arabic is vocalised; meanings are that API's English.

export const NAMES = [
  { n: 1, ar: "الرَّحْمَنُ", tr: "Ar Rahmaan", meaning: "The Beneficent" },
  { n: 2, ar: "الرَّحِيمُ", tr: "Ar Raheem", meaning: "The Merciful" },
  { n: 3, ar: "الْمَلِكُ", tr: "Al Malik", meaning: "The King / Eternal Lord" },
  { n: 4, ar: "الْقُدُّوسُ", tr: "Al Quddus", meaning: "The Purest" },
  { n: 5, ar: "السَّلاَمُ", tr: "As Salaam", meaning: "The Source of Peace" },
  { n: 6, ar: "الْمُؤْمِنُ", tr: "Al Mu'min", meaning: "The inspirer of faith" },
  { n: 7, ar: "الْمُهَيْمِنُ", tr: "Al Muhaymin", meaning: "The Guardian" },
  { n: 8, ar: "الْعَزِيزُ", tr: "Al Azeez", meaning: "The Precious / The Most Mighty" },
  { n: 9, ar: "الْجَبَّارُ", tr: "Al Jabbaar", meaning: "The Compeller" },
  { n: 10, ar: "الْمُتَكَبِّرُ", tr: "Al Mutakabbir", meaning: "The Greatest" },
  { n: 11, ar: "الْخَالِقُ", tr: "Al Khaaliq", meaning: "The Creator" },
  { n: 12, ar: "الْبَارِئُ", tr: "Al Baari", meaning: "The Maker of Order" },
  { n: 13, ar: "الْمُصَوِّرُ", tr: "Al Musawwir", meaning: "The Shaper of Beauty" },
  { n: 14, ar: "الْغَفَّارُ", tr: "Al Ghaffaar", meaning: "The Forgiving" },
  { n: 15, ar: "الْقَهَّارُ", tr: "Al Qahhaar", meaning: "The Subduer" },
  { n: 16, ar: "الْوَهَّابُ", tr: "Al Wahhaab", meaning: "The Giver of All" },
  { n: 17, ar: "الرَّزَّاقُ", tr: "Ar Razzaaq", meaning: "The Sustainer" },
  { n: 18, ar: "الْفَتَّاحُ", tr: "Al Fattaah", meaning: "The Opener" },
  { n: 19, ar: "اَلْعَلِيْمُ", tr: "Al 'Aleem", meaning: "The Knower of all" },
  { n: 20, ar: "الْقَابِضُ", tr: "Al Qaabid", meaning: "The Constrictor" },
  { n: 21, ar: "الْبَاسِطُ", tr: "Al Baasit", meaning: "The Reliever" },
  { n: 22, ar: "الْخَافِضُ", tr: "Al Khaafid", meaning: "The Abaser" },
  { n: 23, ar: "الرَّافِعُ", tr: "Ar Raafi'", meaning: "The Exalter" },
  { n: 24, ar: "الْمُعِزُّ", tr: "Al Mu'iz", meaning: "The Bestower of Honour" },
  { n: 25, ar: "المُذِلُّ", tr: "Al Mudhil", meaning: "The Humiliator" },
  { n: 26, ar: "السَّمِيعُ", tr: "As Samee'", meaning: "The Hearer of all" },
  { n: 27, ar: "الْبَصِيرُ", tr: "Al Baseer", meaning: "The Seer of all" },
  { n: 28, ar: "الْحَكَمُ", tr: "Al Hakam", meaning: "The Judge" },
  { n: 29, ar: "الْعَدْلُ", tr: "Al 'Adl", meaning: "The Just" },
  { n: 30, ar: "اللَّطِيفُ", tr: "Al Lateef", meaning: "The Subtle One" },
  { n: 31, ar: "الْخَبِيرُ", tr: "Al Khabeer", meaning: "The All Aware" },
  { n: 32, ar: "الْحَلِيمُ", tr: "Al Haleem", meaning: "The Forebearing" },
  { n: 33, ar: "الْعَظِيمُ", tr: "Al 'Azeem", meaning: "The Maginificent" },
  { n: 34, ar: "الْغَفُورُ", tr: "Al Ghafoor", meaning: "The Great Forgiver" },
  { n: 35, ar: "الشَّكُورُ", tr: "Ash Shakoor", meaning: "The Rewarder of Thankfulness" },
  { n: 36, ar: "الْعَلِيُّ", tr: "Al 'Aliyy", meaning: "The Highest" },
  { n: 37, ar: "الْكَبِيرُ", tr: "Al Kabeer", meaning: "The Greatest" },
  { n: 38, ar: "الْحَفِيظُ", tr: "Al Hafeez", meaning: "The Preserver" },
  { n: 39, ar: "المُقيِت", tr: "Al Muqeet", meaning: "The Nourisher" },
  { n: 40, ar: "الْحسِيبُ", tr: "Al Haseeb", meaning: "The Reckoner" },
  { n: 41, ar: "الْجَلِيلُ", tr: "Al Jaleel", meaning: "The Majestic" },
  { n: 42, ar: "الْكَرِيمُ", tr: "Al Kareem", meaning: "The Generous" },
  { n: 43, ar: "الرَّقِيبُ", tr: "Ar Raqeeb", meaning: "The Watchful One" },
  { n: 44, ar: "الْمُجِيبُ", tr: "Al Mujeeb", meaning: "The Responder to Prayer" },
  { n: 45, ar: "الْوَاسِعُ", tr: "Al Waasi'", meaning: "The All Comprehending" },
  { n: 46, ar: "الْحَكِيمُ", tr: "Al Hakeem", meaning: "The Perfectly Wise" },
  { n: 47, ar: "الْوَدُودُ", tr: "Al Wudood", meaning: "The Loving One" },
  { n: 48, ar: "الْمَجِيدُ", tr: "Al Majeed", meaning: "The Most Glorious One" },
  { n: 49, ar: "الْبَاعِثُ", tr: "Al Baa'ith", meaning: "The Resurrector" },
  { n: 50, ar: "الشَّهِيدُ", tr: "Ash Shaheed", meaning: "The Witness" },
  { n: 51, ar: "الْحَقُّ", tr: "Al Haqq", meaning: "The Truth" },
  { n: 52, ar: "الْوَكِيلُ", tr: "Al Wakeel", meaning: "The Trustee" },
  { n: 53, ar: "الْقَوِيُّ", tr: "Al Qawiyy", meaning: "The Possessor of all strength" },
  { n: 54, ar: "الْمَتِينُ", tr: "Al Mateen", meaning: "The Forceful" },
  { n: 55, ar: "الْوَلِيُّ", tr: "Al Waliyy", meaning: "The Protector" },
  { n: 56, ar: "الْحَمِيدُ", tr: "Al Hameed", meaning: "The Praised" },
  { n: 57, ar: "الْمُحْصِي", tr: "Al Muhsi", meaning: "The Appraiser" },
  { n: 58, ar: "الْمُبْدِئُ", tr: "Al Mubdi", meaning: "The Originator" },
  { n: 59, ar: "الْمُعِيدُ", tr: "Al Mu'eed", meaning: "The Restorer" },
  { n: 60, ar: "الْمُحْيِي", tr: "Al Muhiy", meaning: "The Giver of life" },
  { n: 61, ar: "اَلْمُمِيتُ", tr: "Al Mumeet", meaning: "The Taker of life" },
  { n: 62, ar: "الْحَيُّ", tr: "Al Haiyy", meaning: "The Ever Living" },
  { n: 63, ar: "الْقَيُّومُ", tr: "Al Qayyoom", meaning: "The Self Existing" },
  { n: 64, ar: "الْوَاجِدُ", tr: "Al Waajid", meaning: "The Finder" },
  { n: 65, ar: "الْمَاجِدُ", tr: "Al Maajid", meaning: "The Glorious" },
  { n: 66, ar: "الْواحِدُ", tr: "Al Waahid", meaning: "The Only One" },
  { n: 67, ar: "اَلاَحَدُ", tr: "Al Ahad", meaning: "The One" },
  { n: 68, ar: "الصَّمَدُ", tr: "As Samad", meaning: "The Supreme Provider" },
  { n: 69, ar: "الْقَادِرُ", tr: "Al Qaadir", meaning: "The Powerful" },
  { n: 70, ar: "الْمُقْتَدِرُ", tr: "Al Muqtadir", meaning: "The Creator of all power" },
  { n: 71, ar: "الْمُقَدِّمُ", tr: "Al Muqaddim", meaning: "The Expediter" },
  { n: 72, ar: "الْمُؤَخِّرُ", tr: "Al Mu’akhir", meaning: "The Delayer" },
  { n: 73, ar: "الأوَّلُ", tr: "Al Awwal", meaning: "The First" },
  { n: 74, ar: "الآخِرُ", tr: "Al Aakhir", meaning: "The Last" },
  { n: 75, ar: "الظَّاهِرُ", tr: "Az Zaahir", meaning: "The Manifest" },
  { n: 76, ar: "الْبَاطِنُ", tr: "Al Baatin", meaning: "The Hidden" },
  { n: 77, ar: "الْوَالِي", tr: "Al Waali", meaning: "The Governor" },
  { n: 78, ar: "الْمُتَعَالِي", tr: "Al Muta’ali", meaning: "The Supreme One" },
  { n: 79, ar: "الْبَرُّ", tr: "Al Barr", meaning: "The Doer of Good" },
  { n: 80, ar: "التَّوَابُ", tr: "At Tawwaab", meaning: "The Guide to Repentence" },
  { n: 81, ar: "الْمُنْتَقِمُ", tr: "Al Muntaqim", meaning: "The Avenger" },
  { n: 82, ar: "العَفُوُّ", tr: "Al Afuww", meaning: "The Forgiver" },
  { n: 83, ar: "الرَّؤُوفُ", tr: "Ar Ra’oof", meaning: "The Clement" },
  { n: 84, ar: "مَالِكُ الْمُلْكِ", tr: "Maalik Ul Mulk", meaning: "The Owner / Soverign of All" },
  { n: 85, ar: "ذُوالْجَلاَلِ وَالإكْرَامِ", tr: "Dhu Al Jalaali Wa Al Ikraam", meaning: "Possessor of Majesty and Bounty" },
  { n: 86, ar: "الْمُقْسِطُ", tr: "Al Muqsit", meaning: "The Equitable One" },
  { n: 87, ar: "الْجَامِعُ", tr: "Al Jaami'", meaning: "The Gatherer" },
  { n: 88, ar: "الْغَنِيُّ", tr: "Al Ghaniyy", meaning: "The Rich One" },
  { n: 89, ar: "الْمُغْنِي", tr: "Al Mughi", meaning: "The Enricher" },
  { n: 90, ar: "اَلْمَانِعُ", tr: "Al Maani'", meaning: "The Preventer of harm" },
  { n: 91, ar: "الضَّارَّ", tr: "Ad Daaarr", meaning: "The Creator of the harmful" },
  { n: 92, ar: "النَّافِعُ", tr: "An Naafi’", meaning: "The Bestower of Benefits" },
  { n: 93, ar: "النُّورُ", tr: "An Noor", meaning: "The Light" },
  { n: 94, ar: "الْهَادِي", tr: "Al Haadi", meaning: "The Guider" },
  { n: 95, ar: "الْبَدِيعُ", tr: "Al Badi'", meaning: "The Originator" },
  { n: 96, ar: "اَلْبَاقِي", tr: "Al Baaqi", meaning: "The Everlasting One" },
  { n: 97, ar: "الْوَارِثُ", tr: "Al Waarith", meaning: "The Inhertior" },
  { n: 98, ar: "الرَّشِيدُ", tr: "Ar Rasheed", meaning: "The Most Righteous Guide" },
  { n: 99, ar: "الصَّبُورُ", tr: "As Saboor", meaning: "The Patient One" },
];
