// The 114 surahs — index only. Names and ayah counts from
// api.alquran.cloud/v1/surah; `order` (revelation order) and the translated
// meanings from api.quran.com/api/v4/chapters in each language.
// The ayahs themselves are fetched per surah when opened: the whole Qur'an with
// a translation is roughly 5MB, which has no business in the bundle.
// `before` is how many ayahs precede this surah in the mushaf order.

export const TOTAL_AYAHS = 6236;

export const SURAHS = [
  { n: 1, ar: "سُورَةُ ٱلْفَاتِحَةِ", en: "Al-Faatiha", meaning: { en: "The Opener", az: "Kitabı açan" }, ayahs: 7, place: "Meccan", order: 5, before: 0 },
  { n: 2, ar: "سُورَةُ البَقَرَةِ", en: "Al-Baqara", meaning: { en: "The Cow", az: "İnək" }, ayahs: 286, place: "Medinan", order: 87, before: 7 },
  { n: 3, ar: "سُورَةُ آلِ عِمۡرَانَ", en: "Aal-i-Imraan", meaning: { en: "Family of Imran", az: "İmran ailəsi" }, ayahs: 200, place: "Medinan", order: 89, before: 293 },
  { n: 4, ar: "سُورَةُ النِّسَاءِ", en: "An-Nisaa", meaning: { en: "The Women", az: "Qadınlar" }, ayahs: 176, place: "Medinan", order: 92, before: 493 },
  { n: 5, ar: "سُورَةُ المَائـِدَةِ", en: "Al-Maaida", meaning: { en: "The Table Spread", az: "Süfrə" }, ayahs: 120, place: "Medinan", order: 112, before: 669 },
  { n: 6, ar: "سُورَةُ الأَنۡعَامِ", en: "Al-An'aam", meaning: { en: "The Cattle", az: "Davar" }, ayahs: 165, place: "Meccan", order: 55, before: 789 },
  { n: 7, ar: "سُورَةُ الأَعۡرَافِ", en: "Al-A'raaf", meaning: { en: "The Heights", az: "Sədd" }, ayahs: 206, place: "Meccan", order: 39, before: 954 },
  { n: 8, ar: "سُورَةُ الأَنفَالِ", en: "Al-Anfaal", meaning: { en: "The Spoils of War", az: "Qənimətlər" }, ayahs: 75, place: "Medinan", order: 88, before: 1160 },
  { n: 9, ar: "سُورَةُ التَّوۡبَةِ", en: "At-Tawba", meaning: { en: "The Repentance", az: "Tövbə" }, ayahs: 129, place: "Medinan", order: 113, before: 1235 },
  { n: 10, ar: "سُورَةُ يُونُسَ", en: "Yunus", meaning: { en: "Jonah", az: "Yunus" }, ayahs: 109, place: "Meccan", order: 51, before: 1364 },
  { n: 11, ar: "سُورَةُ هُودٍ", en: "Hud", meaning: { en: "Hud", az: "Hud" }, ayahs: 123, place: "Meccan", order: 52, before: 1473 },
  { n: 12, ar: "سُورَةُ يُوسُفَ", en: "Yusuf", meaning: { en: "Joseph", az: "Yusuf" }, ayahs: 111, place: "Meccan", order: 53, before: 1596 },
  { n: 13, ar: "سُورَةُ الرَّعۡدِ", en: "Ar-Ra'd", meaning: { en: "The Thunder", az: "Göy gurultusu" }, ayahs: 43, place: "Medinan", order: 96, before: 1707 },
  { n: 14, ar: "سُورَةُ إِبۡرَاهِيمَ", en: "Ibrahim", meaning: { en: "Abraham", az: "İbrahim" }, ayahs: 52, place: "Meccan", order: 72, before: 1750 },
  { n: 15, ar: "سُورَةُ الحِجۡرِ", en: "Al-Hijr", meaning: { en: "The Rocky Tract", az: "Hicr" }, ayahs: 99, place: "Meccan", order: 54, before: 1802 },
  { n: 16, ar: "سُورَةُ النَّحۡلِ", en: "An-Nahl", meaning: { en: "The Bee", az: "Bal arısı" }, ayahs: 128, place: "Meccan", order: 70, before: 1901 },
  { n: 17, ar: "سُورَةُ الإِسۡرَاءِ", en: "Al-Israa", meaning: { en: "The Night Journey", az: "Gecə səyahəti" }, ayahs: 111, place: "Meccan", order: 50, before: 2029 },
  { n: 18, ar: "سُورَةُ الكَهۡفِ", en: "Al-Kahf", meaning: { en: "The Cave", az: "Mağara" }, ayahs: 110, place: "Meccan", order: 69, before: 2140 },
  { n: 19, ar: "سُورَةُ مَرۡيَمَ", en: "Maryam", meaning: { en: "Mary", az: "Məryəm" }, ayahs: 98, place: "Meccan", order: 44, before: 2250 },
  { n: 20, ar: "سُورَةُ طه", en: "Taa-Haa", meaning: { en: "Ta-Ha", az: "Ta-ha" }, ayahs: 135, place: "Meccan", order: 45, before: 2348 },
  { n: 21, ar: "سُورَةُ الأَنبِيَاءِ", en: "Al-Anbiyaa", meaning: { en: "The Prophets", az: "Peyğəmbərlər" }, ayahs: 112, place: "Meccan", order: 73, before: 2483 },
  { n: 22, ar: "سُورَةُ الحَجِّ", en: "Al-Hajj", meaning: { en: "The Pilgrimage", az: "Həcc" }, ayahs: 78, place: "Medinan", order: 103, before: 2595 },
  { n: 23, ar: "سُورَةُ المُؤۡمِنُونَ", en: "Al-Muminoon", meaning: { en: "The Believers", az: "Möminlər" }, ayahs: 118, place: "Meccan", order: 74, before: 2673 },
  { n: 24, ar: "سُورَةُ النُّورِ", en: "An-Noor", meaning: { en: "The Light", az: "Nur" }, ayahs: 64, place: "Medinan", order: 102, before: 2791 },
  { n: 25, ar: "سُورَةُ الفُرۡقَانِ", en: "Al-Furqaan", meaning: { en: "The Criterion", az: "Haqqı batildən ayıran" }, ayahs: 77, place: "Meccan", order: 42, before: 2855 },
  { n: 26, ar: "سُورَةُ الشُّعَرَاءِ", en: "Ash-Shu'araa", meaning: { en: "The Poets", az: "Şairlər" }, ayahs: 227, place: "Meccan", order: 47, before: 2932 },
  { n: 27, ar: "سُورَةُ النَّمۡلِ", en: "An-Naml", meaning: { en: "The Ant", az: "Qarışqalar" }, ayahs: 93, place: "Meccan", order: 48, before: 3159 },
  { n: 28, ar: "سُورَةُ القَصَصِ", en: "Al-Qasas", meaning: { en: "The Stories", az: "Əhvalat" }, ayahs: 88, place: "Meccan", order: 49, before: 3252 },
  { n: 29, ar: "سُورَةُ العَنكَبُوتِ", en: "Al-Ankaboot", meaning: { en: "The Spider", az: "Hörümçək" }, ayahs: 69, place: "Meccan", order: 85, before: 3340 },
  { n: 30, ar: "سُورَةُ الرُّومِ", en: "Ar-Room", meaning: { en: "The Romans", az: "Rumlular" }, ayahs: 60, place: "Meccan", order: 84, before: 3409 },
  { n: 31, ar: "سُورَةُ لُقۡمَانَ", en: "Luqman", meaning: { en: "Luqman", az: "Loğman" }, ayahs: 34, place: "Meccan", order: 57, before: 3469 },
  { n: 32, ar: "سُورَةُ السَّجۡدَةِ", en: "As-Sajda", meaning: { en: "The Prostration", az: "Səcdə" }, ayahs: 30, place: "Meccan", order: 75, before: 3503 },
  { n: 33, ar: "سُورَةُ الأَحۡزَابِ", en: "Al-Ahzaab", meaning: { en: "The Combined Forces", az: "Müttəfiqlər" }, ayahs: 73, place: "Medinan", order: 90, before: 3533 },
  { n: 34, ar: "سُورَةُ سَبَإٍ", en: "Saba", meaning: { en: "Sheba", az: "Səba" }, ayahs: 54, place: "Meccan", order: 58, before: 3606 },
  { n: 35, ar: "سُورَةُ فَاطِرٍ", en: "Faatir", meaning: { en: "Originator", az: "Yaradan" }, ayahs: 45, place: "Meccan", order: 43, before: 3660 },
  { n: 36, ar: "سُورَةُ يسٓ", en: "Yaseen", meaning: { en: "Ya Sin", az: "Yasin" }, ayahs: 83, place: "Meccan", order: 41, before: 3705 },
  { n: 37, ar: "سُورَةُ الصَّافَّاتِ", en: "As-Saaffaat", meaning: { en: "Those who set the Ranks", az: "Səf-Səf duranlar" }, ayahs: 182, place: "Meccan", order: 56, before: 3788 },
  { n: 38, ar: "سُورَةُ صٓ", en: "Saad", meaning: { en: "The Letter \"Saad\"", az: "Sad" }, ayahs: 88, place: "Meccan", order: 38, before: 3970 },
  { n: 39, ar: "سُورَةُ الزُّمَرِ", en: "Az-Zumar", meaning: { en: "The Troops", az: "Zümrələr" }, ayahs: 75, place: "Meccan", order: 59, before: 4058 },
  { n: 40, ar: "سُورَةُ غَافِرٍ", en: "Ghafir", meaning: { en: "The Forgiver", az: "Bağışlayan" }, ayahs: 85, place: "Meccan", order: 60, before: 4133 },
  { n: 41, ar: "سُورَةُ فُصِّلَتۡ", en: "Fussilat", meaning: { en: "Explained in Detail", az: "Müfəssəl izah edilmiş" }, ayahs: 54, place: "Meccan", order: 61, before: 4218 },
  { n: 42, ar: "سُورَةُ الشُّورَىٰ", en: "Ash-Shura", meaning: { en: "The Consultation", az: "Şura" }, ayahs: 53, place: "Meccan", order: 62, before: 4272 },
  { n: 43, ar: "سُورَةُ الزُّخۡرُفِ", en: "Az-Zukhruf", meaning: { en: "The Ornaments of Gold", az: "Zinət" }, ayahs: 89, place: "Meccan", order: 63, before: 4325 },
  { n: 44, ar: "سُورَةُ الدُّخَانِ", en: "Ad-Dukhaan", meaning: { en: "The Smoke", az: "Tüstü" }, ayahs: 59, place: "Meccan", order: 64, before: 4414 },
  { n: 45, ar: "سُورَةُ الجَاثِيَةِ", en: "Al-Jaathiya", meaning: { en: "The Crouching", az: "Diz çökənlər" }, ayahs: 37, place: "Meccan", order: 65, before: 4473 },
  { n: 46, ar: "سُورَةُ الأَحۡقَافِ", en: "Al-Ahqaf", meaning: { en: "The Wind-Curved Sandhills", az: "Qumsal təpələr" }, ayahs: 35, place: "Meccan", order: 66, before: 4510 },
  { n: 47, ar: "سُورَةُ مُحَمَّدٍ", en: "Muhammad", meaning: { en: "Muhammad", az: "Muhəmməd" }, ayahs: 38, place: "Medinan", order: 95, before: 4545 },
  { n: 48, ar: "سُورَةُ الفَتۡحِ", en: "Al-Fath", meaning: { en: "The Victory", az: "Zəfər" }, ayahs: 29, place: "Medinan", order: 111, before: 4583 },
  { n: 49, ar: "سُورَةُ الحُجُرَاتِ", en: "Al-Hujuraat", meaning: { en: "The Rooms", az: "Otaqlar" }, ayahs: 18, place: "Medinan", order: 106, before: 4612 },
  { n: 50, ar: "سُورَةُ قٓ", en: "Qaaf", meaning: { en: "The Letter \"Qaf\"", az: "Qaf" }, ayahs: 45, place: "Meccan", order: 34, before: 4630 },
  { n: 51, ar: "سُورَةُ الذَّارِيَاتِ", en: "Adh-Dhaariyat", meaning: { en: "The Winnowing Winds", az: "Toz torpağı səpələyənlər" }, ayahs: 60, place: "Meccan", order: 67, before: 4675 },
  { n: 52, ar: "سُورَةُ الطُّورِ", en: "At-Tur", meaning: { en: "The Mount", az: "Dağ" }, ayahs: 49, place: "Meccan", order: 76, before: 4735 },
  { n: 53, ar: "سُورَةُ النَّجۡمِ", en: "An-Najm", meaning: { en: "The Star", az: "Ulduz" }, ayahs: 62, place: "Meccan", order: 23, before: 4784 },
  { n: 54, ar: "سُورَةُ القَمَرِ", en: "Al-Qamar", meaning: { en: "The Moon", az: "Ay" }, ayahs: 55, place: "Meccan", order: 37, before: 4846 },
  { n: 55, ar: "سُورَةُ الرَّحۡمَٰن", en: "Ar-Rahmaan", meaning: { en: "The Beneficent", az: "Rəhmli olan Allah" }, ayahs: 78, place: "Medinan", order: 97, before: 4901 },
  { n: 56, ar: "سُورَةُ الوَاقِعَةِ", en: "Al-Waaqia", meaning: { en: "The Inevitable", az: "Vaqiə" }, ayahs: 96, place: "Meccan", order: 46, before: 4979 },
  { n: 57, ar: "سُورَةُ الحَدِيدِ", en: "Al-Hadid", meaning: { en: "The Iron", az: "Dəmir" }, ayahs: 29, place: "Medinan", order: 94, before: 5075 },
  { n: 58, ar: "سُورَةُ المُجَادلَةِ", en: "Al-Mujaadila", meaning: { en: "The Pleading Woman", az: "Mübahisə edən qadın" }, ayahs: 22, place: "Medinan", order: 105, before: 5104 },
  { n: 59, ar: "سُورَةُ الحَشۡرِ", en: "Al-Hashr", meaning: { en: "The Exile", az: "Toplama" }, ayahs: 24, place: "Medinan", order: 101, before: 5126 },
  { n: 60, ar: "سُورَةُ المُمۡتَحنَةِ", en: "Al-Mumtahana", meaning: { en: "She that is to be examined", az: "İmtahana çəkilən qadın" }, ayahs: 13, place: "Medinan", order: 91, before: 5150 },
  { n: 61, ar: "سُورَةُ الصَّفِّ", en: "As-Saff", meaning: { en: "The Ranks", az: "Səf" }, ayahs: 14, place: "Medinan", order: 109, before: 5163 },
  { n: 62, ar: "سُورَةُ الجُمُعَةِ", en: "Al-Jumu'a", meaning: { en: "The Congregation, Friday", az: "Cümə" }, ayahs: 11, place: "Medinan", order: 110, before: 5177 },
  { n: 63, ar: "سُورَةُ المُنَافِقُونَ", en: "Al-Munaafiqoon", meaning: { en: "The Hypocrites", az: "Münafiqlər" }, ayahs: 11, place: "Medinan", order: 104, before: 5188 },
  { n: 64, ar: "سُورَةُ التَّغَابُنِ", en: "At-Taghaabun", meaning: { en: "The Mutual Disillusion", az: "Qarşılıqlı aldanma" }, ayahs: 18, place: "Medinan", order: 108, before: 5199 },
  { n: 65, ar: "سُورَةُ الطَّلَاقِ", en: "At-Talaaq", meaning: { en: "The Divorce", az: "Boşanma" }, ayahs: 12, place: "Medinan", order: 99, before: 5217 },
  { n: 66, ar: "سُورَةُ التَّحۡرِيمِ", en: "At-Tahrim", meaning: { en: "The Prohibition", az: "Qadağan" }, ayahs: 12, place: "Medinan", order: 107, before: 5229 },
  { n: 67, ar: "سُورَةُ المُلۡكِ", en: "Al-Mulk", meaning: { en: "The Sovereignty", az: "Mülk" }, ayahs: 30, place: "Meccan", order: 77, before: 5241 },
  { n: 68, ar: "سُورَةُ القَلَمِ", en: "Al-Qalam", meaning: { en: "The Pen", az: "Qələm" }, ayahs: 52, place: "Meccan", order: 2, before: 5271 },
  { n: 69, ar: "سُورَةُ الحَاقَّةِ", en: "Al-Haaqqa", meaning: { en: "The Reality", az: "Haqq olan" }, ayahs: 52, place: "Meccan", order: 78, before: 5323 },
  { n: 70, ar: "سُورَةُ المَعَارِجِ", en: "Al-Ma'aarij", meaning: { en: "The Ascending Stairways", az: "Dərəcələr" }, ayahs: 44, place: "Meccan", order: 79, before: 5375 },
  { n: 71, ar: "سُورَةُ نُوحٍ", en: "Nooh", meaning: { en: "Noah", az: "Nuh" }, ayahs: 28, place: "Meccan", order: 71, before: 5419 },
  { n: 72, ar: "سُورَةُ الجِنِّ", en: "Al-Jinn", meaning: { en: "The Jinn", az: "Cinlər" }, ayahs: 28, place: "Meccan", order: 40, before: 5447 },
  { n: 73, ar: "سُورَةُ المُزَّمِّلِ", en: "Al-Muzzammil", meaning: { en: "The Enshrouded One", az: "Bürünmüş" }, ayahs: 20, place: "Meccan", order: 3, before: 5475 },
  { n: 74, ar: "سُورَةُ المُدَّثِّرِ", en: "Al-Muddaththir", meaning: { en: "The Cloaked One", az: "Örtünmüş" }, ayahs: 56, place: "Meccan", order: 4, before: 5495 },
  { n: 75, ar: "سُورَةُ القِيَامَةِ", en: "Al-Qiyaama", meaning: { en: "The Resurrection", az: "Qiyamət" }, ayahs: 40, place: "Meccan", order: 31, before: 5551 },
  { n: 76, ar: "سُورَةُ الإِنسَانِ", en: "Al-Insaan", meaning: { en: "The Man", az: "İnsan" }, ayahs: 31, place: "Medinan", order: 98, before: 5591 },
  { n: 77, ar: "سُورَةُ المُرۡسَلَاتِ", en: "Al-Mursalaat", meaning: { en: "The Emissaries", az: "Göndərilənlər" }, ayahs: 50, place: "Meccan", order: 33, before: 5622 },
  { n: 78, ar: "سُورَةُ النَّبَإِ", en: "An-Naba", meaning: { en: "The Tidings", az: "Xəbər" }, ayahs: 40, place: "Meccan", order: 80, before: 5672 },
  { n: 79, ar: "سُورَةُ النَّازِعَاتِ", en: "An-Naazi'aat", meaning: { en: "Those who drag forth", az: "Can alanlar" }, ayahs: 46, place: "Meccan", order: 81, before: 5712 },
  { n: 80, ar: "سُورَةُ عَبَسَ", en: "Abasa", meaning: { en: "He Frowned", az: "Qaşqabağını tökdü" }, ayahs: 42, place: "Meccan", order: 24, before: 5758 },
  { n: 81, ar: "سُورَةُ التَّكۡوِيرِ", en: "At-Takwir", meaning: { en: "The Overthrowing", az: "Sarınma" }, ayahs: 29, place: "Meccan", order: 7, before: 5800 },
  { n: 82, ar: "سُورَةُ الانفِطَارِ", en: "Al-Infitaar", meaning: { en: "The Cleaving", az: "Parçalanma" }, ayahs: 19, place: "Meccan", order: 82, before: 5829 },
  { n: 83, ar: "سُورَةُ المُطَفِّفِينَ", en: "Al-Mutaffifin", meaning: { en: "The Defrauding", az: "Çəkidə və ölçüdə aldadanlar" }, ayahs: 36, place: "Meccan", order: 86, before: 5848 },
  { n: 84, ar: "سُورَةُ الانشِقَاقِ", en: "Al-Inshiqaaq", meaning: { en: "The Sundering", az: "Yarılma" }, ayahs: 25, place: "Meccan", order: 83, before: 5884 },
  { n: 85, ar: "سُورَةُ البُرُوجِ", en: "Al-Burooj", meaning: { en: "The Mansions of the Stars", az: "Bürclər" }, ayahs: 22, place: "Meccan", order: 27, before: 5909 },
  { n: 86, ar: "سُورَةُ الطَّارِقِ", en: "At-Taariq", meaning: { en: "The Nightcommer", az: "Gecə yolçusu" }, ayahs: 17, place: "Meccan", order: 36, before: 5931 },
  { n: 87, ar: "سُورَةُ الأَعۡلَىٰ", en: "Al-A'laa", meaning: { en: "The Most High", az: "Ən uca" }, ayahs: 19, place: "Meccan", order: 8, before: 5948 },
  { n: 88, ar: "سُورَةُ الغَاشِيَةِ", en: "Al-Ghaashiya", meaning: { en: "The Overwhelming", az: "Bürüyən" }, ayahs: 26, place: "Meccan", order: 68, before: 5967 },
  { n: 89, ar: "سُورَةُ الفَجۡرِ", en: "Al-Fajr", meaning: { en: "The Dawn", az: "Dan yeri" }, ayahs: 30, place: "Meccan", order: 10, before: 5993 },
  { n: 90, ar: "سُورَةُ البَلَدِ", en: "Al-Balad", meaning: { en: "The City", az: "Şəhər" }, ayahs: 20, place: "Meccan", order: 35, before: 6023 },
  { n: 91, ar: "سُورَةُ الشَّمۡسِ", en: "Ash-Shams", meaning: { en: "The Sun", az: "Günəş" }, ayahs: 15, place: "Meccan", order: 26, before: 6043 },
  { n: 92, ar: "سُورَةُ اللَّيۡلِ", en: "Al-Lail", meaning: { en: "The Night", az: "Gecə" }, ayahs: 21, place: "Meccan", order: 9, before: 6058 },
  { n: 93, ar: "سُورَةُ الضُّحَىٰ", en: "Ad-Dhuhaa", meaning: { en: "The Morning Hours", az: "Səhər" }, ayahs: 11, place: "Meccan", order: 11, before: 6079 },
  { n: 94, ar: "سُورَةُ الشَّرۡحِ", en: "Ash-Sharh", meaning: { en: "The Relief", az: "Açma" }, ayahs: 8, place: "Meccan", order: 12, before: 6090 },
  { n: 95, ar: "سُورَةُ التِّينِ", en: "At-Tin", meaning: { en: "The Fig", az: "Əncir" }, ayahs: 8, place: "Meccan", order: 28, before: 6098 },
  { n: 96, ar: "سُورَةُ العَلَقِ", en: "Al-Alaq", meaning: { en: "The Clot", az: "Laxtalanmış qan" }, ayahs: 19, place: "Meccan", order: 1, before: 6106 },
  { n: 97, ar: "سُورَةُ القَدۡرِ", en: "Al-Qadr", meaning: { en: "The Power", az: "Qədr gecəsi" }, ayahs: 5, place: "Meccan", order: 25, before: 6125 },
  { n: 98, ar: "سُورَةُ البَيِّنَةِ", en: "Al-Bayyina", meaning: { en: "The Clear Proof", az: "Açıq-aydın dəlil" }, ayahs: 8, place: "Medinan", order: 100, before: 6130 },
  { n: 99, ar: "سُورَةُ الزَّلۡزَلَةِ", en: "Az-Zalzala", meaning: { en: "The Earthquake", az: "Zəlzələ" }, ayahs: 8, place: "Medinan", order: 93, before: 6138 },
  { n: 100, ar: "سُورَةُ العَادِيَاتِ", en: "Al-Aadiyaat", meaning: { en: "The Courser", az: "Çapanlar" }, ayahs: 11, place: "Meccan", order: 14, before: 6146 },
  { n: 101, ar: "سُورَةُ القَارِعَةِ", en: "Al-Qaari'a", meaning: { en: "The Calamity", az: "Qorxuya salan" }, ayahs: 11, place: "Meccan", order: 30, before: 6157 },
  { n: 102, ar: "سُورَةُ التَّكَاثُرِ", en: "At-Takaathur", meaning: { en: "The Rivalry in world increase", az: "Çoxluqla hərislik" }, ayahs: 8, place: "Meccan", order: 16, before: 6168 },
  { n: 103, ar: "سُورَةُ العَصۡرِ", en: "Al-Asr", meaning: { en: "The Declining Day", az: "Axşam çağı" }, ayahs: 3, place: "Meccan", order: 13, before: 6176 },
  { n: 104, ar: "سُورَةُ الهُمَزَةِ", en: "Al-Humaza", meaning: { en: "The Traducer", az: "Tənə edən" }, ayahs: 9, place: "Meccan", order: 32, before: 6179 },
  { n: 105, ar: "سُورَةُ الفِيلِ", en: "Al-Fil", meaning: { en: "The Elephant", az: "Fil" }, ayahs: 5, place: "Meccan", order: 19, before: 6188 },
  { n: 106, ar: "سُورَةُ قُرَيۡشٍ", en: "Quraish", meaning: { en: "Quraysh", az: "Qureyş" }, ayahs: 4, place: "Meccan", order: 29, before: 6193 },
  { n: 107, ar: "سُورَةُ المَاعُونِ", en: "Al-Maa'un", meaning: { en: "The Small kindnesses", az: "Xırda xuruş" }, ayahs: 7, place: "Meccan", order: 17, before: 6197 },
  { n: 108, ar: "سُورَةُ الكَوۡثَرِ", en: "Al-Kawthar", meaning: { en: "The Abundance", az: "Bolluq" }, ayahs: 3, place: "Meccan", order: 15, before: 6204 },
  { n: 109, ar: "سُورَةُ الكَافِرُونَ", en: "Al-Kaafiroon", meaning: { en: "The Disbelievers", az: "Kafirlər" }, ayahs: 6, place: "Meccan", order: 18, before: 6207 },
  { n: 110, ar: "سُورَةُ النَّصۡرِ", en: "An-Nasr", meaning: { en: "The Divine Support", az: "Kömək" }, ayahs: 3, place: "Medinan", order: 114, before: 6213 },
  { n: 111, ar: "سُورَةُ المَسَدِ", en: "Al-Masad", meaning: { en: "The Palm Fiber", az: "Xurma lifi" }, ayahs: 5, place: "Meccan", order: 6, before: 6216 },
  { n: 112, ar: "سُورَةُ الإِخۡلَاصِ", en: "Al-Ikhlaas", meaning: { en: "The Sincerity", az: "Səmimi etiqad" }, ayahs: 4, place: "Meccan", order: 22, before: 6221 },
  { n: 113, ar: "سُورَةُ الفَلَقِ", en: "Al-Falaq", meaning: { en: "The Daybreak", az: "Sübh" }, ayahs: 5, place: "Meccan", order: 20, before: 6225 },
  { n: 114, ar: "سُورَةُ النَّاسِ", en: "An-Naas", meaning: { en: "Mankind", az: "İnsanlar" }, ayahs: 6, place: "Meccan", order: 21, before: 6230 },
];
